[package]
name = "mqtt_broker"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
mio = "0.8"  # Hoặc phiên bản mới nhất
pin-project-lite = "0.2"